export const AUTH_ERROR_CODES = {
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  REQUIRES_EMAIL_VERIFICATION: 'REQUIRES_EMAIL_VERIFICATION',
  EMAIL_NOT_CONFIRMED: 'EMAIL_NOT_CONFIRMED',
} as const;

export type AuthErrorCode =
  (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
